function h = add_patch(img_size, scale, h)
if nargin<2
    scale = 1;
    if nargin<1
        img_size = 1000;
    end
end
if nargin == 3
    img_size = size(h.CData,1);
end

patch('Faces',[1,2,3,4],...
    'Vertices',[img_size - round(0.5*img_size/scale),1;...
    img_size,1;...
    img_size,round(0.5*img_size/scale);...
    img_size - round(0.5*img_size/scale),round(0.5*img_size/scale)],...
    'FaceColor','r','EdgeColor','r',...
    'FaceAlpha',.5,...
    'LineWidth',1);